Awesome books: with ES6
studiosnabeel/awesomebooks-with-es6 pull request #1
Opened 2022-11-07 15:55 UTC by studiosnabeel

#Learning objectives
Use ES6 modules to write modular JavaScript.
Learn how to use proper ES6 syntax.
Understand the improvements that ES6 brings to JavaScript.
Use npm as a software package system.

In this project, I will restructure my Awesome books app code. The goal is to make it more organized by using modules. I have also practiced the ES6 syntax that I learned.

2022-11-07 16:36 UTC, emmiiorji requested changes
Hi @studiosnabeel, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![a little more](https://user-images.githubusercontent.com/20554583/200076873-30b10773-7347-4e81-9511-930fe733ca71.gif)

## Good Highlights✔

- Meaningful commit messages
- Good readme documentation
- Linter checks are passing


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-07 16:36 UTC, emmiiorji commented on modules/switch.js
> +      linkTwo.style.color = 'black';
[Optional] I recommend here that you create CSS classes with styles for the different scenarios, then simply add and remove those classes. That will make the code more concise.

2022-11-07 16:36 UTC, emmiiorji commented on README.md
> +- code .
Your readme looks great. Kindly update it with instructions on how to launch the application after cloning.

2022-11-07 16:36 UTC, emmiiorji commented on index.js
> +  const author = document.querySelector('#author').value;
[Optional] In order to avoid saving an all-spaces string, I recommend that you trim (`str.trim()`) the values and save only if the resulting string is not empty.

![image](https://user-images.githubusercontent.com/20554583/200364524-7447684b-99d9-4529-98cc-f1f5f03fe2b4.png)

2022-11-08 08:04 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @studiosnabeel  👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 08:08 UTC, merged